- name: Ensure required variables are defined
  fail: msg="Required variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - openwisp2fw_source_dir
    - openwisp2fw_generator_dir
    - openwisp2fw_bin_dir
    - openwisp2fw_organizations

- name: Ensure directories used by the playbook exist
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ openwisp2fw_source_dir }}"
    - "{{ openwisp2fw_generator_dir }}"
    - "{{ openwisp2fw_bin_dir }}"

# ensure ansible user has write permissions in the directories it uses
# this saves the annoiance of a "Permission Denied" error at the end of the process
- name: Write test file to check permissions
  # this task never fails but registers a variable that is checked later
  failed_when: false
  register: permission_check
  file:
    dest: "{{ item }}/__test__"
    state: touch
  with_items:
    - "{{ openwisp2fw_source_dir }}"
    - "{{ openwisp2fw_generator_dir }}"
    - "{{ openwisp2fw_bin_dir }}"

# remove test file created in the previous task
- name: Remove test file
  # always remove __test__ files and ignore failures
  failed_when: false
  file:
    dest: "{{ item }}/__test__"
    state: "absent"
  with_items:
    - "{{ openwisp2fw_source_dir }}"
    - "{{ openwisp2fw_generator_dir }}"
    - "{{ openwisp2fw_bin_dir }}"

# fail playbook loud if the variable permission_check contains "Permission denied"
- name: Verify result of permission check
  fail:
    msg: "{{ ansible_user }} doesn't have write permission to write in {{ item.item }}"
  when: '"module_stdout" in item and "Permission denied" in item.module_stdout'
  with_items: "{{ permission_check.results }}"
