- name: Update APT package cache
  apt: update_cache=yes
  become: true

- name: Upgrade make dependencies
  apt: name={{ item }} state=latest
  with_items: openwisp2fw_apt_make_dependencies
  become: true
