- include: 1-apt.yml
  tags: [openwisp2fw, apt]

- include: 2-openwrt.yml
  tags: [openwisp2fw, openwrt]
  when: openwisp2fw_base_recompile

- include: 3-generator.yml
  tags: [openwisp2fw, generator]
