# ensure required variables are defined
- fail: msg="Required variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - openwisp2fw_source_dir
    - openwisp2fw_generator_dir
    - openwisp2fw_bin_dir
    - openwisp2fw_organizations
  # this task must be always executed
  tags: [openwisp2fw, install, compile, generator, build]

# install system dependencies
- include: 1-apt.yml
  tags: [openwisp2fw, install]

# compile OpenWRT/LEDE in order to produce the ImageBuilder(s)
# these actions are performed only if "recompile=1" is passed as an extra param
# or if openwisp2fw_source_recompile == true
- include: 2-compile.yml
  tags: [openwisp2fw, compile]
  when: openwisp2fw_source_recompile

# prepare ImageGenerator directory and files
# but do not compile images yet
- include: 3-generator.yml
  tags: [openwisp2fw, generator]

# build images for each organization and flavour
# store binaries in versioned directories
- include: 4-build.yml
  tags: [openwisp2fw, build]
